print(" mencoba membuat program py")
print(" menulis tugas akhir ")
print(" tambahan tugas akhir ")
print("ini dari vbc ")
print(" ini dari vbc lagi")
print(" ini dari vbx lagi lagi ")
print(" baru lagi ")
print(" buat program dari vb c")
print(" ini dari github ")
print(" ini buat program dari vb c")
print(" ini tambahan program dari repo ")
